# Generated by Django 5.1.7 on 2025-04-13 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_remove_salesbill_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesbill',
            old_name='date',
            new_name='bill_date',
        ),
    ]
