# Generated by Django 5.1.7 on 2025-04-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0004_rename_date_salesbill_bill_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesbill',
            name='bill_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
