# Generated by Django 5.1.7 on 2025-04-15 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0005_alter_salesbill_bill_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesbill',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
    ]
