# Generated by Django 5.1.7 on 2025-04-18 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0006_salesbill_discount_price_delete_discount'),
        ('funds', '0007_alter_expense_expense_type_alter_expense_fund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesbill',
            name='fund',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='salesbills', to='funds.fund'),
            preserve_default=False,
        ),
    ]
