# Generated by Django 5.1.7 on 2025-04-18 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0007_alter_salesbill_fund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesbill',
            name='customer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
