# Generated by Django 5.1.7 on 2025-04-19 05:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0008_alter_salesbill_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesbill',
            name='bill_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesbill',
            name='bill_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesbill',
            name='bill_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
