# Generated by Django 5.1.7 on 2025-04-19 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0009_salesbill_bill_datetime_salesbill_bill_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesbill',
            name='bill_time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
