# Generated by Django 5.1.7 on 2025-04-21 03:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0010_alter_salesbill_bill_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesbill',
            name='bill_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salesbill',
            name='bill_time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
