# Generated by Django 5.2 on 2025-06-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0011_alter_salesbill_bill_date_alter_salesbill_bill_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesbilltype',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
