# Generated by Django 5.2 on 2025-05-25 13:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='selling_price',
            new_name='selling_price_retail',
        ),
        migrations.AddField(
            model_name='stock',
            name='selling_price_wholesale',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
