# Generated by Django 5.2 on 2025-06-01 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_selling_price_stock_selling_price_retail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktype',
            name='unit',
            field=models.CharField(choices=[('', 'None'), ('mtr', 'Meter'), ('ml', 'Milliliter')], default='', max_length=3),
        ),
    ]
