# Generated by Django 5.1.7 on 2025-04-16 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
