# Generated by Django 5.1.7 on 2025-04-19 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0007_alter_expense_expense_type_alter_expense_fund'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='date',
            new_name='datetime',
        ),
        migrations.AddField(
            model_name='expense',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
