# Generated by Django 5.1.7 on 2025-04-19 10:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0009_expense_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='datetime',
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='expense',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
