# Generated by Django 5.2 on 2025-05-25 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0010_remove_expense_datetime_alter_expense_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('from_fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='funds.fund')),
                ('to_fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='funds.fund')),
            ],
        ),
    ]
