# Generated by Django 5.2 on 2025-06-01 19:05

import funds.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0011_fundtransfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=funds.models.get_current_date),
        ),
        migrations.AlterField(
            model_name='expense',
            name='time',
            field=models.TimeField(default=funds.models.get_current_time),
        ),
    ]
