# Generated by Django 5.1.7 on 2025-04-13 11:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bills', '0002_initial'),
        ('funds', '0002_initial'),
        ('inventory', '0002_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('return_quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('return_price_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='funds.fund')),
                ('stockset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='inventory.stockset')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('return_quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('return_price_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='bills.salesbill')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='funds.fund')),
                ('stockset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='inventory.stockset')),
            ],
        ),
    ]
