# Generated by Django 5.1.7 on 2025-04-13 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='fund',
        ),
    ]
