# Generated by Django 5.1.7 on 2025-04-21 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_remove_sale_fund'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='datetime',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
