# Generated by Django 5.2 on 2025-06-01 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_alter_purchase_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
